### ISSUE TITLE
Show amount of collateral in given curve

### ISSUE THREAD

**Issue by deamme** [AragonBlack/fundraising#100]
There's no way in the UI to see the total amount of collateral of ANT, DAI etc. Either we show the amount of collateral or we link to Etherscan.

@cryptodani Suggested to add the metrics to the `Bonded token` box in the `Reserve Settings` tab.

Another solution would be to add it to `Key metrics` in `Overview` tab. We need to extend the key metrics component somehow to accommodate for that change.

**Comment by cryptodani** [comment]
To have in reserve settings a link to the etherscans of each collateral various contracts,
except if its divided in some many contracts its better to show a sum

**Comment by osarrouy** [comment]
I’m not sure to understand. How is this different from the_Reserve_ entry in the overview metrics tab ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cryptodani** [comment]
Was tinking of using the Aragon UI component and a link to etherscan to check the whole curve contract....but we have view transaction for each order which then gives the curve contract so in the end should be understandable by end user

**Comment by osarrouy** [comment]
Closing for now. We re-open for v2.
