### ISSUE TITLE
Polishing stuff

### ISSUE THREAD

**Issue by osarrouy** [AragonBlack/fundraising#121]
**Presale**
- [x] The `exchangeRate` is now expressed in PPM for precision's sake. This should be taken into account in how the estimated total return is displayed in the `New Contribution` panel [and probably handled in the app reducer too]. @xseignard 
- [x] The local state [`FUNDING`, `GOAL_REACHED`, etc.] is not automatically updated. One must reload the page for the new state to be reflected in the frontend [this may be a problem with polling] @xseignard 
- [x] When the presale has reached it's goal [state is `GOAL_REACHED`] the clock showing time until the end of presale is still ticking. We should remove it cause it's not relevant anymore and makes people feel like they should still wait for something. @xseignard 
- [x] Update presale percentage calculation in contract. @osarrouy 
- [x] The `New Contribution` panel does not automatically close when the transaction is passed. @xseignard 

**Overview**
- [x] I feel like the `Key Metrics` box title is weirdly aligned [somehow to much on the right]. This may be me but let's double check it's consistent with the design system. @deamme 
- [x] The `Token address` should be renamed `Share token address` for the consistency's matters. @xseignard 

**Orders / My orders tab**
- [x] All field headers should be capped / upper case. For now some are, some are not. @xseignard 
- [x] The `tokens` field should be renamed `SHARES` @xseignard 
- [x] The `token price` field should be renamed `SHARE PRICE` @xseignard 
- [x] The `order amount` field should be renamed `VALUE` @xseignard 
- [x] The `ACTION` header [only in `My Orders`] is weirdly centered ... @deamme 
- [x] Ideally the icons should be updated: `Pending` should show a clock and `Over` should show a clock with a green ticker over it [showing that time wise it's now ok] @deamme 
- [x] When we CVS export the orders list and there are orders worth more than 1000$ it fails. This is because this orders are displayed with a comma: like $1,000.00. This mess up with the CVS format which uses commas to separate columns. @xseignard 

**New order panel**
- [x] The balance displayed should be rounded to two decimals. The same rounding should also by applied in the Presale new contribution panel. @xseignard 
- [x] An error message should be displayed [and the transaction prevented to be sent] if the orders are to big and are gonna break slippage ...

**Reserve settings tab**
- [x] The `Edit reserve settings` title should be remove cause it just introduce redundancies. @xseignard 
- [x] The right panel [`Bonded Token`] should be renamed `Shares` for consistency's matters. @xseignard  
- [x] I think it would make sense to add the `SHARE` token address in that right panel too. @xseignard 
- [x] The DAI and ANT collateralization ratio are wrong cause they are divided by 100. It should be 10% and 1% and are displayed as 0.10% and 0.01%. I guess it's because the division by 100 is made both in the reducer and in the frontend. We should remove that last one. @xseignard 
- [x] The tooltip descriptions should be updated. @osarrouy 
- [x] The radspec description for the tap update should be expressed per month and not per block @osarrouy 
- [x] The error message when one tries to update the rate or floor should be updated. For the rate: `You cannot increase the tap rate more than once per month`. For the floor: `You cannot decrease the tap floor more than once per month` @xseignard 
- [x] The current tap rate the is displayed in the action right panel when one wanna update it is not rounded which make it look weird. For instance I updated to 500 DAI a month and If I open the panel to update it again it's displayed as `500,0000000000000832`which looks kinda weird. It should be rounded here as it is rounded elsewhere @xseignard

**Comment by cryptodani** [comment]
- [ ] When clicking withdraw the field description is "Transfer about 1026.76 DAI from the reserve to the beneficiary on Fundraising." It is not clear (from the text) if this is about transfering the tap to beneficary or for curve liquidation
