### ISSUE TITLE
FundraisingMultisigTemplate - _ensureTokenIsContractOrETH should fail instead of returning bool

### ISSUE THREAD

**Issue by cleanunicorn** [AragonBlack/fundraising#123]
#### Description

The constructor accepts `_aragonID`, `_miniMeFactory`, `_dai` and `_ant` which represent addresses to contracts to be used.

https://github.com/AragonBlack/fundraising/blob/3d2f1837da62c0384edc05a944c46496f919ceb0/templates/multisig/contracts/FundraisingMultisigTemplate.sol#L69-L72

The `_ensureAragonIdIsValid` and `_ensureMiniMeFactoryIsValid` are defined as:

https://github.com/aragon/dao-templates/blob/master/shared/contracts/BaseTemplate.sol#L392-L394

https://github.com/aragon/dao-templates/blob/master/shared/contracts/BaseTemplate.sol#L377-L379

And they fail if the requirements are not met.

While the `_ensureTokenIsContractOrETH` method is defined as:

https://github.com/AragonBlack/fundraising/blob/3d2f1837da62c0384edc05a944c46496f919ceb0/templates/multisig/contracts/FundraisingMultisigTemplate.sol#L573-L575

Returning a bool instead of requiring the bool to be `true`.

#### Remediation

Rewrite the method `_ensureTokenIsContractOrETH` to:

```solidity
function _ensureTokenIsContractOrETH(address _token) internal view returns (bool) {
    require(isContract(_token) || _token == ETH);
}
```

Also please add an error message.

**Comment by osarrouy** [comment]
Fixed by #131
