### ISSUE TITLE
Presale - Naming of error should be slightly different

### ISSUE THREAD

**Issue by cleanunicorn** [AragonBlack/fundraising#127]
#### Description

There is a minor naming issue with the constant `ERROR_INCORRECT_ETH_VALUE`. 

It is defined here:

https://github.com/AragonBlack/fundraising/blob/3d2f1837da62c0384edc05a944c46496f919ceb0/apps/presale/contracts/Presale.sol#L37

And used in a `require` here:

https://github.com/AragonBlack/fundraising/blob/3d2f1837da62c0384edc05a944c46496f919ceb0/apps/presale/contracts/Presale.sol#L166-L170

The minor issue is that it refers to ether also when the token contribution is incorrect.

#### Remediation

My suggestion is to change it to:

```solidity
string private constant ERROR_INCORRECT_CONTRIBUTION_VALUE      = "PRESALE_INCORRECT_CONTRIBUTION_VALUE";
```

To fix tests it should also be changed here:
https://github.com/AragonBlack/fundraising/blob/3d2f1837da62c0384edc05a944c46496f919ceb0/apps/presale/test/Contribute.test.js#L137

https://github.com/AragonBlack/fundraising/blob/3d2f1837da62c0384edc05a944c46496f919ceb0/apps/presale/test/Contribute.test.js#L142-L143

**Comment by osarrouy** [comment]
Fixed by #131
