### ISSUE TITLE
Change default ANT slippage guard

### ISSUE THREAD

**Issue by cryptodani** [AragonBlack/fundraising#140]
ANT slippage guard is by default 100% (none). Especially for arbitrageurs and in an environemnt where there may be lower liquidity than DAI curve this is not conductive to trading. Fixing this could be problematic if someone puts %slippage guard very high on DAI (unlikely)

**Comment by osarrouy** [comment]
100% is not no slippage: it is a 100% slippage which means the price can double [so this is a very high slippage]. You think we should make it bigger or smaller ?
