### ISSUE TITLE
Give tokenholders the ability to start votes

### ISSUE THREAD

**Issue by john-light** [AragonBlack/fundraising#145]
In the Fundraising setup flow it says:

> This architecture grants most of the governance rights to shareholders, to protect their investment. However, this also requires the organization to be able to mitigate situations where a shareholder could own the whole organization by owning more than 50% of the shares.
> 
> This is why shareholder votes, where most of the organization’s decisions are made, can only be opened and initiated by the board.

This seems to interfere with the ability for tokenholders to hold the board accountable. If I am a dishonest board, then my strategy here would be to simply never open a vote as demanded by tokenholders. Then I will continue to receive funding from the tap until the reserves run out.

I propose giving tokenholders the ability to create votes, or at least making this a configurable parameter, and once the Aragon Court is live then it can take care of situations where a >50% tokenholder tries to create malicious votes (this is its initial use-case after all).

**Comment by osarrouy** [comment]
Hmmmm,

This is an issue we are aware of. But i’m really reluctant to change it as long as the court is not really there.  Cause it would mean in the meanwhile that everyone could buy the organization and all of its funds ...


You think this is a problem if we wait for the court to be out and running before we update it ?

**Comment by john-light** [comment]
@osarrouy it's hard to say what is the bigger threat: a dishonest majority of tokenholders, or a dishonest board. But I think there should at least be an option for users to make that determination themselves. 

One other idea: if a "ragequit" like mechanism or other kind of time-delay is added to proposal execution it would give honest tokeholders a chance to exit before any dishonest majority can siphon off all of the funds.
