### ISSUE TITLE
Fundraising timeline copy is confusing

### ISSUE THREAD

**Issue by john-light** [AragonBlack/fundraising#148]
I started the sale on Oct 16 and the presale reached its goal that same day. The sale then became open for trading. However on the timeline it says that trading "can be open" on Oct 18. Wouldn't it be more accurate if this said something like "Refunds issued if presale does not meet its goal" since trading can be open before the presale end date if the presale does meet its goal?

![presale4](https://user-images.githubusercontent.com/9424721/66970033-dd20d380-f040-11e9-9fc0-751395e953cf.png)

**Comment by lkngtn** [comment]
I think this may actually be a bug, because afaik the intention is that trading should not be able to be started until after the pre-sale phase ends.

**Comment by osarrouy** [comment]
Fixed on the new frontend version. The wording is now 'Contributors can ask for refund if presale fails'.
