### ISSUE TITLE
MarketMaker: support artificial collateral injections

### ISSUE THREAD

**Issue by izqui** [AragonBlack/fundraising#150]
For tokens like ANJ and ARA, it is possible that we will need to inject some extra ANT initially to make it more appealing for protocol workers and kickoff the security of these networks by increasing their market cap and creating a strong supply.

If this ANT (which would come either from the AA or ANT inflation) is directly transferred to the reserve, it will create a massive arbitrage opportunity and it can be almost fully captured by a frontrunner (similar to the problem outlined in #149).

I'm not sure about what the best solution for this is, perhaps when the injection is performed increasing the virtual balance of the collateral token and then interpolate it back to its original value across a large number of batches.

As in #149, I don't see this as a hard requirement for launch, but something that we definitely need for ANJ (targeting BC deployment in early December).

**Comment by bingen** [comment]
I'm not sure I'm getting this one. I don't fully get why we need to inject ANT, but taking that as an assumption, can the AA just buy ANJ (and therefore put ANT into the reserve) and not activate those ANJ so they don't get drafted?

**Comment by osarrouy** [comment]
I’m not sure to get it either ? What would be the goal of injecting ANT if not increasing the price [but then actually offering massive arbitrage opportunities] ?

**Comment by osarrouy** [comment]
Moved to #179.
