### ISSUE TITLE
Controller: add support for 'approveAndCall'

### ISSUE THREAD

**Issue by izqui** [AragonBlack/fundraising#151]
MiniMe and a few other ERC20 implementations have an `approveAndCall` function that allows performing an ERC20 approval and then calling a contract which can act on the approval. This would allow 1 transaction buy and sells for tokens that support this, with ANT and all the TM's tokens with support for it.

Implementation wise it would be almost trivial to support it, you can check how we did it in Aragon Court for reference: 

https://github.com/aragon/aragon-court/blob/development/contracts/registry/JurorsRegistry.sol#L447-L457

Note: `msg.sender` on this function will always be the token address, so the authentication check would need to be performed against the `receiver` address in the call.

Note 2: some tokens have broken implementations of `approveAndCall` https://github.com/ConsenSys/Tokens/pull/45

I would definitely include this for v1 given how easy it is to implement it and the UX benefits from only needing one transaction. Support for this should be implemented at the aragonAPI level (https://github.com/aragon/aragon.js/issues/398), which should detect if the token address passed in the pretransaction supports `approveAndCall` and use it if so.

**Comment by osarrouy** [comment]
Moved to #179.
