### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by osarrouy** [AragonBlack/fundraising#21]
Now that the implementation is almost ready we should start working on the documentation to have everything ready for the Rinkeby pre-release and mainnet release. This documentation should include:
- [ ] Overview. A simple explanation of what Fundraising is, what is its architecture and how it works.
- [ ] User guide [basic]. A simple user guide with a couple of screenshots about how to use Fundraising frontend.
- [ ] User guide [advanced]. An advanced user guide about to use Fundraising through the CLI, how to do arbitrage, etc.
- [ ] Reference. Reference API for the `fundraising` library.

Before we start working on this we should handle a couple of questions though:
- [x] Platform. How / where do we aggregate the doc ? EDIT.-: We now have a gitbook at https://fundraising.aragon.black
- [x] Coordination. How is in charge of what ? EDIT: This is @cryptodani

**Comment by cryptodani** [comment]
Starting Overview+User Guide Basic based on front-end status

**Comment by osarrouy** [comment]
@cryptodani Can you keep us up-to-date with that one ?

**Comment by cryptodani** [comment]
Yep! Will update you as User Guide gets updated/uploaded and overview finalised. 
Can one of you @xseignard @osarrouy take on the reference API?

**Comment by xseignard** [comment]
I can take on the reference API.
@osarrouy can you confirm that when we speak about reference API, it's about documenting the `AragonFundraisingController` smart contract, or all the smart contracts ?

**Comment by deamme** [comment]
Also add documentation for different workflows for developing and also for deploying.

**Comment by osarrouy** [comment]
Thanks @deamme !

@xseignard We should document all the smart contracts. It think it would be wiser to wait for the second audit feedback before we do so, though [just to be sure everything is stabililized before we do the doc]

**Comment by cryptodani** [comment]
- [ ] Finalize Basic overview/Preface 

- [ ] Finalize ressource/reading list

User Guide Basic:
- [ ] Update screens, flows and descriptions with v2 upload

- [ ] Setup v2 local deployment for simulating votes, permissions updates curve withdraw and add screes and flows to guide

- [ ] Send User Guide to A1 for inclusion to Help desk

User Guide Advanced:

- [ ] Technical coordination for writing on Market Maker and Controller 

- [ ] Write Agent Guide

- [ ] Write Arbitrage guide when decision is final about collaterals and method

- [ ] Write and display some use cases for using other apps in conjunction with curve such as Uniswap, dot voting, ENS etc with local deployment of V2 (maybe better included as a medium articles series)

Theoritical Overview:

- [ ] Edit with what other sections in mind
