### ISSUE TITLE
apps/kit-aragon-fundraising/package.json dependency issue

### ISSUE THREAD

**Issue by xmaysonnave** [AragonBlack/fundraising#33]
Pulled the new kit this morning and was unable to compile it.
The dependencies refers to @aragon/os 4.0.1 who does not contain @aragon/os/contracts/common/SafeERC20.sol
It sounds that SafeERC20 appears in @aragon/os:4.1.0
Upgraded to 4.1.0 and compilation went fine.
Thanks

**Comment by gh1dra** [comment]
Hey @xmaysonnave thanks for testing this out for us, we've updated dependencies in the `dev`, we should be merging an update to `master` soon.

**Comment by osarrouy** [comment]
This should be fixed on the `next` branch where `apps/kit-aragon-fundraising` has been replaced by `templates/multisig` and now uses the new template scheme.
