### ISSUE TITLE
Update apiary WP

### ISSUE THREAD

**Issue by osarrouy** [AragonBlack/fundraising#4]
Update apiary WP according to the new architecture and batched orders mechanism.

**Comment by lkngtn** [comment]
I can update the WP, but wondering if we shouldn't create a separate document here with the technical specification/requirements?

**Comment by osarrouy** [comment]
Didn't even see your reply. Sorry @lkngtn. I've initialized a gitbook synced with the `doc` branch of this repo. Maybe this could be the place ?

https://aragonblack.gitbook.io/fundraising/
