### ISSUE TITLE
Market maker does not respect token vesting restrictions in the token manager

### ISSUE THREAD

**Issue by lkngtn** [AragonBlack/fundraising#44]
There should be a check to ensure that a user is not able to "sell" tokens which have not yet been vested. We should probably do a check to make sure that the sell amount is less than or equal to the users "spendableBalance". 

https://github.com/aragon/aragon-apps/blob/78ea5923b1c64dcb916ab381b1648c416af95e11/apps/token-manager/contracts/TokenManager.sol#L297

**Comment by osarrouy** [comment]
I’m gonna double check that.

**Comment by osarrouy** [comment]
Fixed by 809687389d2d9108ed3ad21d374c14ea655697a9.
