### ISSUE TITLE
Pass buyer / seller address in openBuyOrder and openSellOrder function parameters

### ISSUE THREAD

**Issue by GriffGreen** [AragonBlack/fundraising#46]
As a user that want to mint a token that is non transferable, I want to use my metamask address to interact with the bonding curve, but I want the token to end up in a different address (a gnosis safe, multisig or a hardware wallet)

What do you think? Is it too late to have a proxy buy?

@lkngtn @osarrouy :-)

**Comment by osarrouy** [comment]
Hey @GriffGreen !

This is something we can of course do for buy orders but then you would have the problem of how to pass sell orders with that address if you can't use your gnosis safe or multisig wallet to easily interact with the frontend.

The way I see you would still need to send back your bonds from gnosis safe or multisig or whatever to metamask to open these sell orders so I'm wondering if it would make sense [cause then you can do the same when opening buy orders].

What would be your take on that ?

**Comment by Pol-Lanski** [comment]
Hey @osarrouy !
What I understand from what you say is that you would need to perform the sell order from a frontend that is not compatible with gnosis safe or multisig, is that right?

I think if you were to make them available for transfering to metamask, the token would already be transferable and therefore more susceptible to scrutiny as security, etc. 

To keep it non-transferable, ideally a metamask address could do the buy order (and effectively pay) but passing another address to receive the tokens, which would still be non-transferable. If this receiving address was a multisig/gnosis safe... is there any way that they could sell it directly without transferring them? 

Best,
Pol

**Comment by osarrouy** [comment]
This would indeed be doable ...

**Comment by osarrouy** [comment]
Moved to #179.
