### ISSUE TITLE
Maximum call stack size exceeded while compiling app/market-maker-bancor

### ISSUE THREAD

**Issue by xmaysonnave** [AragonBlack/fundraising#48]
1 - The app/market-maker-bancor/package.json contains :
"scripts": {
    ...
    "compile": "truffle compile",
    ...
  },
While compiling solc crashed with the following :
RangeError: Maximum call stack size exceeded
2 - I fixed the issue with the following :
"scripts": {
    ...
    "compile": "node --stack-size=4096 ./node_modules/.bin/truffle compile",
    ...
  },
Thanks

**Comment by osarrouy** [comment]
The whole monorepo and configuration has been updated. Closing it as it should now be ok on the `next` branch. Feel free to re-open if not :)
