### ISSUE TITLE
Change "Returned" status copy

### ISSUE THREAD

**Issue by john-light** [AragonBlack/fundraising#56]
Currently, after an order has been claimed, the status is changed to "Returned". I recommend changing to "Claimed" to indicate that the order has been claimed.

**Comment by osarrouy** [comment]
Not being a native english speaker I'm not sure of what is clearer for the end user so I'll trust you on that you american guy ;)

@xseignard or @deamme Can you update that ?

**Comment by xseignard** [comment]
I'll do it

**Comment by john-light** [comment]
> @osarrouy: Not being a native english speaker I'm not sure of what is clearer for the end user so I'll trust you on that you american guy ;)

"Returned" almost makes it seem like I would be getting my DAI or ANT back from a buy order, whereas "claimed" makes it clear that I'm claiming the tokens bought in the batch (and aligns with the "claim" button I click to do so).

Thank you for being receptive to feedback :pray:

**Comment by osarrouy** [comment]
This is now fixed in the cleaned version of the UI [merged in next].
