### ISSUE TITLE
High gas limit

### ISSUE THREAD

**Issue by john-light** [AragonBlack/fundraising#57]
When I create a buy order, the second tx to actually place the order (after the approval tx) shows up in MetaMask with a default gas limit of ~6.6 million gas. This is almost a whole block worth of gas. Does it really take this much gas? If not, is it possible to make the default gas limit closer to the actual limit needed? If so, is there a way to lower the amount of gas necessary for a buy order? 6.6 million is quite a lot.

**Comment by osarrouy** [comment]
This one is weird ... An order definitely does not use 6.6M gas but more something around 300k worth of gas ... I have no idea why metamask set it that high by default.

Once more this is the kind of things that are handled by the client so I'm gonna double check that ...

**Comment by sohkai** [comment]
You can specify a hardcoded gas limit in the api call via the transaction options (`{ gas: ... }`) if you know what the limit should be.

There are some cases where Metamask / Infura give us awkward gas limits, and it's hard to pinpoint exactly why sometimes.

**Comment by osarrouy** [comment]
Thanks @sohkai,

That's weird indeed but gonna hardcode a gas limit in that case.

@xseignard Could you hardcode a gas limit of 400000 in the frontend when orders are open ?

**Comment by osarrouy** [comment]
This seems to be fixed in the latest contracts versions.
