### ISSUE TITLE
Refactor Orders/MyOrders components

### ISSUE THREAD

**Issue by xseignard** [AragonBlack/fundraising#63]
We don't need 2 components here.
We should merge them into one.

**Comment by deamme** [comment]
This was also the intial design. I don't mind merging it into one but one problem I see right now is that we are going to get too many columns, since we also need to fit in a new column called "Actions" which is from the `MyOrder` component.

**Comment by xseignard** [comment]
Even if we keep the current design with 2 tabs, only one component should be necessary.
Passing a prop to the component should let us control what to display on each tabs (which is pretty similar)
If you're motivated by this one @deamme feel free to assign yourself.

**Comment by deamme** [comment]
This is not a high priority for me for now.
