### ISSUE TITLE
Review responsiveness of the Order filters

### ISSUE THREAD

**Issue by xseignard** [AragonBlack/fundraising#75]
With some filters activated, we can end up with something like this:
![Capture d’écran 2019-09-04 à 16.21.41.png](https://images.zenhubusercontent.com/5cd97a6c818d2f78607e43dc/26858f5a-608b-4a8d-8a4c-1d9efcbcb692)

**Comment by deamme** [comment]
This is going to be partially fixed with https://github.com/AragonBlack/fundraising/issues/68

**Comment by xseignard** [comment]
OK, I close this issue then
