### ISSUE TITLE
Update tap increase related permissions

### ISSUE THREAD

**Issue by osarrouy** [AragonBlack/fundraising#82]
For now both `tap` updates and `maxTapRateIncreasePercentage` updates are granted to share holders only. I just got an insight from the audit team who believes it would make more sense to:

1. Grant tap updates to the board members [those updates would be controlled by `maxTapRateIncreasePercentage` anyhow]
2. Grant `maxTapRateIncreasePercentage` updates to share holders

Their take is that otherwise the `maxTapRateIncreasePercentage` is pointless if controlled by the same people than the one updating the tap [if you can't update the tap as much as you want you can just update `maxTapRateIncreasePercentage` first] which is relevant.

My only fear is that if we do so we should also add a max `maxTapFloorIncreasePercentage` with the same rational because the `UPDATE_TAPPED_TOKEN_ROLE` allows you to modify both the tap rate and the tap floor.

@lkngtn What would be your take on that one ?

**Comment by lkngtn** [comment]
I tend to disagree with the auditors on this one. I think it's totally valid to have to go through shareholders for both actions, even if one action is significantly less controversial. 

My opinion is to leave this as is, and orgs could certainly choose to make it more permissive by granting the board the tap update permission.
